### ISSUE TITLE
HttpClient is intended to be instantiated once and re-used throughout the life of an application

### ISSUE THREAD

**Issue by Simplicitdk** [SolidStateGroup/bullet-train-dotnet-client#1]
https://github.com/SolidStateGroup/bullet-train-dotnet-client/blob/12413ec6b940479feec5df1180377aa226003d04/BulletTrainClient.cs#L158

HttpClient is intended to be instantiated once and re-used throughout the life of an application. Instantiating an HttpClient class for every request will exhaust the number of sockets available under heavy loads. This will result in SocketException errors. See
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netframework-4.7.2

Be aware of the DNS issue described here
http://byterot.blogspot.com/2016/07/singleton-httpclient-dns.html

**Comment by ssg-luke** [comment]
Hi @Simplicitdk, thanks for reporting this. I've resolved the issue in #2
